### ISSUE TITLE
(obvious) Don't think this is working with Grails 1.4 

### ISSUE THREAD

**Issue by johnlabarge** [jkuehn/gorm-mongodb#8]
I'm fairly new to grails.  I was able to install the plugin using grails 1.4, but when I tried to create a domain class I got a compilation error.   I then grabbed the source, ran grails upgrade and then grails package-plugin, the result of which was a different exception.  Just putting this here so folks know that it's not ready for grails 1.4 just yet.
